### PR TITLE
Remove typed rackunit code and depend on other package

### PR DESCRIPTION
**Pull request by jackfirth**
Rackunit now has a `rackunit-typed` package that contains this code. The package catalog is down at the moment and `rackunit-typed` has not been added to it yet, so this won't compile.

### CODE REVIEW

**Comment by samth** [comment]
Looks good, but we shouldn't merge until `rackunit-typed` is available.

Also `rackunit-typed` should be added as a dependency of `main-distribution`.

**Comment by jackfirth** [comment]
The `rackunit-typed` package is now in the package catalog, and I opened racket/main-distribution#1 to add it to the main distribution.

**Comment by samth** [comment]
I restarted the build.

**Comment by jackfirth** [comment]
The integration tests timed out, are they supposed to take that long?

**Comment by bennn** [comment]
All checks passed!

**Comment by jackfirth** [comment]
I don't have write access, so merge whenever

**Pull request merged**
