### PR TITLE
port typed-racket contract to late-neg projections

### PR DESCRIPTION
**Pull request by rfindler**
I didn't try to run any test suites for this (well, I did make sure DrRacket starts up). I hear that creating the pull request triggers something to run the tests on this commit, so I'm looking forward to seeing that in action!

### CODE REVIEW

**Comment by samth** [comment]
Looks good, and the test suites did pass, as you should be able to see on the pull request page. :)

Thanks for doing this!

**Comment by rfindler** [comment]
If I force push to the branch I created, will the pull request pick that up (and let me fix the grammatical error in my commit message)?

**Comment by florence** [comment]
Yes. The pull request blindly follows the branch it was created from.

**Comment by rfindler** [comment]
Looks like more tests pass:
```
racket -l- typed-racket-test --all
.............................................3535 success(es) 0 failure(s) 0 error(s) 3535 test(s) run
```

Okay if I push?

**Comment by samth** [comment]
Yes.

**Comment by rfindler** [comment]
I don't seem to have a close button here, otherwise I'd push it.

**Comment by samth** [comment]
It got marked merged by your push (GitHub is smart like that).

**Pull request merged**
