### PR TITLE
Improve the Typed Racket Guide to bring it up-to-date with modern TR

### PR DESCRIPTION
**Pull request by lexi-lambda**
This is a work-in-progress branch. I'm currently just opening this pull request to receive feedback on my changes as well as suggestions for additional improvements.

Anyway, the guide has definitely become rather outdated. I think its current state leaves a lot of room for potential confusion for new users of the language. I'm going to try and improve the guide both to update obsolete information and hopefully include some additional points to help better explain TR without needing to drop into the reference.

Here's a list of my current plans, along with what I've completed. Additional suggestions are welcome.

- [x] Remove usages of legacy forms
- [x] Improve the section on recursive types to eliminate `Rec`
- [ ] Add a section on using TR with the class system
- [ ] Add a section on TR best practices

The "best practices" section was suggested by @stamourv, and I think it's a good idea, but I'm not entirely sure what sorts of things should be included. Any thoughts on that would also be appreciated.

### CODE REVIEW

**Comment by samth** [comment]
We don't want to drop the entire discussion about `Rec`, but I think emphasizing the implicit form is right. Maybe a paragraph at the end of that section?

**Comment by samth** [comment]
Other than those comments, this is great!

**Comment by stamourv** [comment]
@samth: Re `Rec`: IMO, dropping the discussion makes sense for the guide. It should definitely be kept for the reference, of course.

**Comment by samth** [comment]
Looks good with the one comment.

**Comment by lexi-lambda** [comment]
Closing this; will open a new PR when I get around to integrating the remaining updates (for post-6.2).

**Pull request closed without merging**
