### PR TITLE
Fix overlap mask error

### LINKED ISSUE #542: mask-accessor: contract violation   expected: mask?   given: #f
### What version of Racket are you using?
6.9.0.1

### What program did you run?
```racket
#lang typed/racket
(struct (A) S ([f : A]))
(define-type T (∩ (S Nonnegative-Integer) (S Nonpositive-Integer)))
```

### What should have happened?

The type `T` should be defined as `(S Zero)`. Note that the bug is not related to arithmetic types, it also occurs with other types like `String` and `Symbol`.

### If you got an error message, please include it here.

```
.racket/snapshot/pkgs/typed-racket-lib/typed-racket/types/overlap.rkt:40:0: mask-accessor: contract violation
  expected: mask?
  given: #f
```

Might be related to #447.

### PR DESCRIPTION
**Pull request by pnwamk**
fixes #542

### CODE REVIEW

**Comment by pnwamk** [comment]
This PR changes calls to `resolve-once` (which can return #f if a type name is not yet defined) to `resolve` (which always returns a Type), and reduces allocation by extending the `seen` list for overlap only when needed.

Sorry for the whitespace changes -- remember to add `?w=1` to the diff URL to ignore whitespace changes!

**Comment by pnwamk** [comment]
tidy diff link: https://github.com/racket/typed-racket/pull/555/commits/7ef2b54e313323984dbe372ed152dcfbd9ac5ee2?w=1

**Comment by pnwamk** [comment]
there's a `#:no-order` on that clause, so we get it both ways (https://github.com/racket/typed-racket/pull/555/files#diff-5fe8f1857d5552b04caf253b9d9782d7R55)

**Comment by samth** [comment]
Ah, I see now.

**Pull request merged**
