### PR TITLE
Numeric comp testing

### PR DESCRIPTION
**Pull request by pnwamk**
Adds random testing for occurrence typing via numeric comparison ops. I.e., the type of the expression is influenced by the logical propositions that arise from the comparison and the testing ensures the actual result is indeed of the predicted type.

### CODE REVIEW

**Comment by samth** [comment]
Does this test find the previous bug?

**Comment by pnwamk** [comment]
Yes, without the previous commit (445a65705a25697967c41e12d7770a2f360858c4) it discovers the bug w/ NaN comparisons:

```
seed: 914449021
redex-check: <pkgs>/typed-racket-test/tr-random-testing.rkt:265
no counterexamples in 1000 attempts
redex-check: <pkgs>/typed-racket-test/tr-random-testing.rkt:269
no counterexamples in 1000 attempts
redex-check: <pkgs>/typed-racket-test/tr-random-testing.rkt:274
no counterexamples in 1000 attempts
type-before = #f
type-after = (U Negative-Fixnum Negative-Integer-Not-Fixnum Negative-Rational-Not-Integer)
redex-check: <pkgs>/typed-racket-test/tr-random-testing.rkt:278
counterexample found after 233 attempts:
(let* ((x -1/2) (y (* (* 4 +inf.f) (+ 0 0.0)))) (if (<= x y) #f x))
redex-check: <pkgs>/typed-racket-test/tr-random-testing.rkt:278
no counterexamples in 1000 attempts
bad tests (usually typechecking failed): 482
```

**Comment by samth** [comment]
The second commit has some test failures, but otherwise looks good.

**Comment by stamourv** [comment]
Neat!

**Pull request merged**
