### PR TITLE
Fix midi-readwrite.

### PR DESCRIPTION
**Pull request by samth**
Fix compilation of `midi-readwrite`. Review by @stamourv requested.

### CODE REVIEW

**Comment by stamourv** [comment]
LGTM.
Are there other unsafe operations we should get rid of?

**Comment by samth** [comment]
These are the ones that seem to get us in trouble. But I'm particularly interested in your feelings on the last commit, which seems like it's papering over the real problem.

**Comment by stamourv** [comment]
The last commit is fine as a stopgap, but we definitely want to investigate how that `#f` got there.
I assume the test case you added triggers it reliably? If so, I'll look into it.

**Comment by samth** [comment]
`raco pkg install midi-readwrite` :)

**Comment by stamourv** [comment]
Oh, and re "those are the ones that get us in trouble": For now. I think we should reconsider others as well.

**Comment by samth** [comment]
I just skimmed the repo, and I think everything else is either:
* handling some function named `unsafe-...`
* generating unsafe code in the optimizer
* guarded by an immediate test (there was only 1 of these)

**Comment by stamourv** [comment]
Ok, then I guess that was the only one we really ought to remove.

**Comment by stamourv** [comment]
For the sake of having two pairs of eyes on it, I've also done an audit of our uses of `unsafe` ops.
I found one that is not guaranteed to be safe, in the expansion of TR's `for/vector`.
I also found two in the implementation of `seen?`, in `types/current-seen.rkt`. I'm not convinced that they are adequately guarded, so I've added an additional check.
I'll push those changes.

**Pull request merged**
