### PR TITLE
WIP: propagate expected props further down AST for typechecking

### PR DESCRIPTION
**Pull request by pnwamk**
Previously expected propositions were erased frequently and without
any comments explaining why.  Instead of checking propositions at the
leaves of the AST, we would erase expected props at let's and ifs and
typecheck the remaining portion of the AST while propagating up ALL
logical info we learned. Then, once all the logical info from the
leaves of the AST had amassed, we would check if it entailed the
logical expected props that we erased. The problem is that you can
easily get exponential blow-up in the size of propositions using this
strategy, even when we are not interested in the propositions whatsoever.

This PR instead sends expected types _and_ props all the way down when
typechecking, so we can verify any expected logical conclusions at
leaves (and with _much_ smaller propositions to worry
about). Additionally, if an expected prop is present, we simply verify
it is satisfied and _do not_ propagate up any logical info (this is
what gets rid of the old exponential growth).

The added test `slow-parser.rkt` is an example of a program that used
to have typecheck time which grew exponentially in the number of match
clauses, but now checks remarkably faster with what appears to be
linear (or similar) scaling w.r.t. the number of clauses.

NOTE: I've labeled this a WIP since it could easily break obscure
things if I haven't handled everything correctly... so I need to do
some thorough testing still.

### CODE REVIEW

**Comment by samth** [comment]
How do other performance tests fare?

Also, can we test this on as many TR-using pkgs as possible, to avoid the problem with `pfds` that we just saw?

**Comment by pnwamk** [comment]
Performance: I have observed largely no change in any of the benchmarks except the `parser.rkt` example, which, as I stated, had a HUGE improvement. I think this is probably why the previous approach seemed okay: for many programs the "potential blow up" just doesn't register. Also -- I have not measured how this affects any larger scale benchmarks (math library, pict3d, plot, etc).

Also -- maybe there is more trimming that could be done still -- this is definitely just my first try at this poking around trying to keep the size of props down.

Other tests: I'll definitely run a few other libraries through the ringer (pfds, plot, pict3d). We don't have an "extended" test script that does this for us yet, do we? That might be nice to add....

**Comment by pnwamk** [comment]
Oh - one other note. This PR _greatly_ improves the completeness of `check-below` on logical information -- it uses the available info in the environment as well as the expressions logical propositions. Because of this, there may be a nice set of programs w/ non-trivial props that used to have a difficult typechecking but now trivially do (e.g. issue #429).

**Comment by pnwamk** [comment]
Tests done in addition to standard typed-racket-test batch:
- [ ] pfds
- [ ] pict3d
- [ ] plot

**Comment by pnwamk** [comment]
merged via be155fa3e3236caa93ef927e205c45b00d6d6e6e

**Pull request closed without merging**
