### PR TITLE
Make zero? sound with regards to NaN.

### PR DESCRIPTION
**Pull request by shekari**

### CODE REVIEW

**Comment by lexi-lambda** [comment]
Why does `-RealZero` contain `NaN`?

**Comment by shekari** [comment]
@lexi-lambda I'm not sure behind the reasoning, but all flonum types conatin `NaN`.

**Comment by samth** [comment]
Basically, very few closure properties hold on sets of floats that don't include `NaN`

**Comment by stamourv** [comment]
What @samth said.

This PR looks good to me.

**Pull request merged**
