### PR TITLE
Try Updating .travis.yml

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by AlexKnauth** [comment]
I'm getting errors like this:
https://travis-ci.org/racket/typed-racket/builds/62487950#L161
```
Resolving "net-test" via http://www.cs.utah.edu/plt/snapshots/20150513-9049737/catalog/
tcp-connect: connection failed
  address: www.cs.utah.edu
  port number: 80
  step: 6
  system error: Connection timed out; errno=110
  context...:
   /home/travis/racket/collects/net/http-client.rkt:220:0
   /home/travis/racket/collects/net/url.rkt:130:0: http://getpost-impure-port
   /home/travis/racket/collects/net/url.rkt:264:2: redirection-loop
   /home/travis/racket/collects/pkg/private/catalog.rkt:213:6
   /home/travis/racket/collects/pkg/private/catalog.rkt:188:0: read-from-server
   /home/travis/racket/collects/pkg/private/catalog.rkt:138:4: for-loop
   /home/travis/racket/collects/pkg/private/catalog.rkt:130:0: package-catalog-lookup
   /home/travis/racket/collects/pkg/private/catalog.rkt:179:0: package-catalog-lookup-source
   /home/travis/racket/collects/pkg/private/clone-path.rkt:356:0: desc->repo
   /home/travis/racket/collects/pkg/private/clone-path.rkt:45:0: adjust-to-normalize-repos
   /home/travis/racket/collects/pkg/private/install.rkt:804:0: pkg-install134
   /home/travis/racket/collects/racket/file.rkt:368:8
   /home/travis/racket/collects/pkg/raco.rkt: [traversing imports]
The command "raco pkg install --auto --no-setup typed-racket-test/" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by AlexKnauth** [comment]
Now I'm getting errors like this:
https://travis-ci.org/racket/typed-racket/builds/62498431#L176
```
raco test: @(test-responsible '(samth stamourv endobson asumu))
/home/travis/build/racket/typed-racket/typed-racket-lib/typed-racket/utils/sealing-contract.rkt:105:20: class-seal: unbound identifier in module
  in: class-seal
```

**Comment by samth** [comment]
That's because typed racket now depends on head but the snapshots aren't
updated yet. Probably @takikawa should have updated the racket version
number so that TR could depend on the new version.

**Comment by AlexKnauth** [comment]
Ok.

**Comment by AlexKnauth** [comment]
I started it again, and it hasn't finished yet, but I started getting errors like this:
https://travis-ci.org/racket/typed-racket/builds/62533547#L171
```
raco test: @(test-responsible '(samth stamourv endobson asumu))
with-limit: out of time
  context...:
   /home/travis/racket/share/pkgs/sandbox-lib/racket/sandbox.rkt:379:0: call-with-limits
   /home/travis/build/racket/typed-racket/typed-racket-test/gui/succeed/gui-contract.rkt: [running body]
   (submod /home/travis/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt process): [running body]
gui-contract.rkt: raco test: non-zero exit: 1
```
And this:
https://travis-ci.org/racket/typed-racket/builds/62533547#L179
```
raco test: @(test-responsible '(samth stamourv endobson asumu))
Gtk initialization failed for display ":0"
  context...:
   /home/travis/racket/share/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt: [running body]
   /home/travis/racket/share/pkgs/gui-lib/mred/private/wx/gtk/init.rkt: [traversing imports]
   /home/travis/racket/share/pkgs/gui-lib/mred/mred.rkt: [traversing imports]
pr15003.rkt: raco test: non-zero exit: 1
```

**Comment by samth** [comment]
I think you should (a) run `raco setup typed typed-racket typed-racket-test` before running the tests and (b) only run some of the tests. To just run the unit tests, for example, you could do `racket -l typed-racket-test/run -- --unit`.

**Comment by AlexKnauth** [comment]
If I run raco setup, won't that re-compile everything that depends on typed racket though? Not that that would be a bad thing, but to save time that was my thinking. Is there a way to do it without doing that?

**Comment by samth** [comment]
That's why I limited it to just those few collections.

**Comment by AlexKnauth** [comment]
But won't it still realize that there are other collections that depend on those collections?

That's what I was about to say when the build finished.  I guess I was wrong.  Thanks!

**Comment by AlexKnauth** [comment]
I got this error again:
https://travis-ci.org/racket/typed-racket/builds/62596514#L155
```
Resolving "net-test" via http://www.cs.utah.edu/plt/snapshots/20150514-c2cd44c/catalog/
tcp-connect: connection failed
  address: www.cs.utah.edu
  port number: 80
  step: 6
  system error: Connection timed out; errno=110
  context...:
   /home/travis/racket/collects/net/http-client.rkt:220:0
   /home/travis/racket/collects/net/url.rkt:130:0: http://getpost-impure-port
   /home/travis/racket/collects/net/url.rkt:264:2: redirection-loop
   /home/travis/racket/collects/pkg/private/catalog.rkt:213:6
   /home/travis/racket/collects/pkg/private/catalog.rkt:188:0: read-from-server
   /home/travis/racket/collects/pkg/private/catalog.rkt:138:4: for-loop
   /home/travis/racket/collects/pkg/private/catalog.rkt:130:0: package-catalog-lookup
   /home/travis/racket/collects/pkg/private/catalog.rkt:179:0: package-catalog-lookup-source
   /home/travis/racket/collects/pkg/private/clone-path.rkt:356:0: desc->repo
   /home/travis/racket/collects/pkg/private/clone-path.rkt:45:0: adjust-to-normalize-repos
   /home/travis/racket/collects/pkg/private/install.rkt:804:0: pkg-install134
   /home/travis/racket/collects/racket/file.rkt:368:8
   /home/travis/racket/collects/pkg/raco.rkt: [traversing imports]
```

**Comment by samth** [comment]
For reasons that I don't understand, Travis has trouble connecting to Utah. Can you try the northwestern snapshot server?

**Comment by AlexKnauth** [comment]
Ok that worked.  
And since that only ran for 5 min and 5 sec, should we try the full raco setup to re-compile the things that depend on typed racket?

**Comment by AlexKnauth** [comment]
Which tests are being skipped right now?

**Comment by samth** [comment]
Instead of running more of `raco setup`, we should run more tests. You can run `run.rkt --help` to see all the optins, but try adding `--int` for the integration tests first.

**Comment by AlexKnauth** [comment]
Now I'm getting this check-failure:
https://travis-ci.org/racket/typed-racket/builds/62613991#L1247
```
299.88s$ racket -l typed-racket-test/run -- --unit --int
--------------------
Typed Racket Tests > Integration tests > succeed > gui-lang.rkt > #f
Unnamed test 
FAILURE
name:       check-not-exn
location:   typed-racket-test/main.rkt:81:31
params:     #<procedure:...et-test/main.rkt:73:10>
message:    "Exception raised"
exception-me"Gtk initialization failed for display \":0\""
exception:  #(struct:exn:fail "Gtk initialization failed for display \":0\"" #<continuation-mark-set>)
expression: (check-not-exn thnk)
Check failure
--------------------
2967 success(es) 1 failure(s) 0 error(s) 2968 test(s) run
Typed Racket Tests did not pass.
```

**Comment by samth** [comment]
We will need to start an X server and set DISPLAY appropriately. The Travis
docs have instructions on this, I think.

**Comment by AlexKnauth** [comment]
Where?

**Comment by samth** [comment]
http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)

**Comment by AlexKnauth** [comment]
Um, I have no idea what I'm doing here now.
Should I add
```
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```
to the `.travis.yml`, or does it expect `export DISPLAY=:0` instead, or do I have to do something else to ` tell your testing tool process (e.g. Selenium) about that display port`, or ?

**Comment by samth** [comment]
That looks right to me -- racket should automatically handle the DISPLAY variable.

**Comment by AlexKnauth** [comment]
I got this now:
https://travis-ci.org/racket/typed-racket/builds/62684048#L260
```
Xlib:  extension "RANDR" missing on display ":99.0".
```

**Comment by samth** [comment]
That's just a warning, which is fine. Looks like the tests all passed.

**Comment by samth** [comment]
We probably want to (a) split up the tests so that we run `--int`, `--unit` etc separately (that way it'll be clearer what fails), and (b) add the remaining tests. Then this is good to go.

**Comment by AlexKnauth** [comment]
By the way reading the travis docs I found this:
http://docs.travis-ci.com/user/speeding-up-the-build/
Would it make sense to do something like this:
```
env:
  - TEST_SUITE=unit
  - TEST_SUITE=int
  - TEST_SUITE=opt
```
etc. and
```
script:
 - "racket -l typed-racket-test/run -- --$TEST_SUITE"
```
Would something like that make sense?

**Comment by samth** [comment]
That would actually use a bunch more resources (since it would compile TR 3 times), but would get us some parallelism.

**Comment by AlexKnauth** [comment]
I'm getting this now:
https://travis-ci.org/racket/typed-racket/builds/62704318#L276
```
$ racket -l typed-racket-test/run -- --math
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by samth** [comment]
Also, if we run `raco setup math` first it will go much faster (since that's basically what the `--math` test does).

**Comment by AlexKnauth** [comment]
Even with that:
https://travis-ci.org/racket/typed-racket/builds/62711345#L323
```
The command "raco setup --no-docs math" exited with 0.
$ racket -l typed-racket-test/run -- -v --math
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by samth** [comment]
Try it without `--no-docs` -- I bet the test builds the docs too.

**Comment by AlexKnauth** [comment]
That's what this did:
https://travis-ci.org/racket/typed-racket/builds/62710811#L276
And it did the same thing but in the raco setup:
https://travis-ci.org/racket/typed-racket/builds/62710811#L317
```
raco setup: 6 making: <pkgs>/math-lib/math/private/vector
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by samth** [comment]
Hmm. Try it with `-j 1`. Travis doesn't really have multiple cores.

**Comment by samth** [comment]
Also, let's try building the TR docs.

**Comment by AlexKnauth** [comment]
Does this look good?

**Comment by samth** [comment]
Yes, this looks good. Feel free to push after squashing down to 1 commit.

**Pull request merged**
