### PR TITLE
fix intersect, make it (hopefully) commutative

### PR DESCRIPTION
**Pull request by pnwamk**
These changes attempt to make computing type intersections a more commutative operation.

### CODE REVIEW

**Comment by pnwamk** [comment]
This came up while debugging why the ```wrap``` package was broken after some recent TR commits.

**Comment by samth** [comment]
Can you describe what the new approach is here?

**Comment by pnwamk** [comment]
The two main differences are as follows:

1. When we're intersecting two unions, we do so by intersecting their cartesian product from the start (this produces more consistent outputs which are not order dependent).

2. Previously ```intersect``` tried to build a more specific recursive type only when we were intersecting two μ-types. This has been expanded to include all types which can be recursive (i.e. μ's, Names, and Apps) and there is a little bit of back-channeling to report whether or not a recursive type is actually required.

I tried to add comments describing all of the new behavior (since w/o comments the 'why' we're doing it that way would clearly not be apparent).

**Comment by pnwamk** [comment]
3. There is now an explicit check for the ```Error``` type (since that breaks what would otherwise be reasonable, mostly commutative things like checking for subtyping, etc)

**Comment by samth** [comment]
This might be a good case for some random testing, but that can wait for a separate PR.

**Comment by samth** [comment]
I think the discussion in bullet 1 should appear in a comment, otherwise looks good.

**Pull request merged**
