### PR TITLE
Support dotted sequence types

### PR DESCRIPTION
**Pull request by lwhjp**
This mostly follows the same pattern as ListDots and ValuesDots - I haven't attempted to refactor everything into an abstract "dotted type", since the similar parts are only a few lines.

No (new) test failures for me locally, and I haven't managed to break it playing around, but I'd appreciate a review by an experienced pair of eyes.

I think this closes issue #279 and part of #287.

### CODE REVIEW

**Comment by lwhjp** [comment]
I finally have contracts enabled properly now - sorry about the fixups.

**Comment by lwhjp** [comment]
Thanks, will do.

**Comment by lwhjp** [comment]
I've made the following updates:
 - Rebase onto latest master (this resolves the class-tests failure)
 - Add tests for make-do-sequence (both single and multi-valued cases)
 - Added TODOs for potential de-duplication if generic dotted types are supported

**Comment by bennn** [comment]
Can you rebase again to bring in 0c3d314b so that Travis can (hopefully) succeed?

**Comment by lwhjp** [comment]
I've rebased - it looks like all the failures are the same as the nightly builds (i.e., no new failures introduced by this patch)

**Comment by bennn** [comment]
Ok, thanks. LGTM. @samth do you want to look this over?

**Comment by LiberalArtist** [comment]
I just found myself wanting this feature and was delighted to see it's been implemented. Thanks to all for your work.

**Pull request merged**
