### PR TITLE
Add typed/syntax/modread, typed/syntax/srcloc, and typed/syntax/readerr

### PR DESCRIPTION
**Pull request by AlexKnauth**
Typed versions of syntax/modread, syntax/srcloc, and syntax/readerr.

### CODE REVIEW

**Comment by samth** [comment]
Looks great. Why the use of `unsafe` in one place but not the others?

**Comment by AlexKnauth** [comment]
Because both the `(Syntaxof Any)` and `Syntax` contracts weren't working for some reason.

**Comment by samth** [comment]
Right, `(Syntaxof Any)` is tricky, as are syntax contracts in general. But there are other files in this PR that use those contracts; I'm wondering why the difference.

**Comment by AlexKnauth** [comment]
I don't know why. Your right, it's very weird.

**Comment by AlexKnauth** [comment]
Although it might have something to do with whether its in a positive or negative position.

**Comment by AlexKnauth** [comment]
It also might have something to do with whether or not it's in a union, although the contracts in that case might be unsound? Yes, it turns out is, but that's a separate issue.

**Comment by AlexKnauth** [comment]
So, once https://github.com/racket/typed-racket/issues/354 is fixed, `typed/syntax/srcloc` will probably have to use `unsafe-require/typed` as well.

**Comment by AlexKnauth** [comment]
If it's handled in the same way that `(-> (Syntaxof Any) Any)` is handled right now, that is.

**Comment by AlexKnauth** [comment]
So, should I translate `typed/syntax/srcloc` to use `unsafe-require/typed`?

**Comment by samth** [comment]
Which programs would work/not work, depending on what you do?

**Comment by AlexKnauth** [comment]
If I leave it as it is, than a fix for #354 would break this. If I change it to use unsafe, then everything would work, but it wouldn't be protected with a contract, but that's fine because typed code won't pass anything unsafe into it, untyped code won't use the unguarded typed values in any unsafe ways, and we can trust the untyped code to return what it promised just like we can for the other trusted racket libraries.

**Comment by samth** [comment]
In that case, let's use unsafe.

**Comment by AlexKnauth** [comment]
Ok, I've updated it to use `unsafe-require/typed` for both `typed/syntax/modread` and `typed/syntax/srcloc`.

**Comment by samth** [comment]
LGTM

**Pull request merged**
