### PR TITLE
Initial support for typed units in typed racket.

### PR DESCRIPTION
**Pull request by dfeltey**
Most unit forms are supported, including most of the "infer" forms that
infer imports/exports/linkages from the current context.

Notably, none of the structural linking forms for units are supported, and
`define-unit-binding` is also currently unsupported.

TODO: Still needs documentation before merging

### CODE REVIEW

**Comment by dfeltey** [comment]
Signature handling in require/typed is currently unsound, the following program results in a segfault:
```
#lang racket
(module untyped racket
  (provide bad^)
  (define-signature bad^
    (bad
     (define-values (bad-ref) (bad 'not-a-pair)))))
(module typed typed/racket
  (require/typed (submod ".." untyped)
                [#:signature bad^
                             ([bad : (-> (Pairof Symbol Symbol) Symbol)])])
  (: e:bad (-> (Pairof Symbol Symbol) Symbol))
  (define (e:bad p) (car p))
  (define u (unit-from-context (prefix e: bad^)))
  (define-values/invoke-unit u (import) (export bad^)))
(require 'typed)
```
require/typed for signatures should reject signatures that contain definitions since there does not seem to be a way to guard those definitions with contracts.

**Comment by stamourv** [comment]
Do you have an idea how to fix it?

Also, there was another issue you mentioned on Friday during our meeting. What was it again, and what's its status?

**Comment by stamourv** [comment]
@samth, @takikawa: I'll review this PR to the best of my knowledge, and my ask you about specific bits I'm less confident about.

**Comment by stamourv** [comment]
You definitely want a big comment at the top of `check-unit-unit.rkt` explaining the general strategy there (pick apart the expansion of unit forms, look for the info you need for typechecking.)

**Comment by stamourv** [comment]
Ok, I'm done with the first pass. Let me know when you've addressed my comments and I'll do another one.

**Comment by stamourv** [comment]
LGTM

**Comment by stamourv** [comment]
Merged, thanks!

**Pull request closed without merging**
