### PR TITLE
fix a bug where cover+tests could call `syntax-local-introduce` when not transforming

### PR DESCRIPTION
**Pull request by florence**
This is kind of a bad fix for florence/cover#83. But I still have no clue *how* the error mentioned there actually happens.

### CODE REVIEW

**Comment by samth** [comment]
LGTM

**Comment by samth** [comment]
Is this still needed?

**Comment by florence** [comment]
I haven't run cover on TR in a while so IDK that make this necessary still occurs. Let me rerun the tests and figure out (it takes quite a while).

**Comment by florence** [comment]
Yes, this is still needed.

**Comment by florence** [comment]
I'm not sure I understand why the travis build for this failed, and it's not failing locally, so I'm not sure how to proceed on this one.

**Pull request closed without merging**
