### PR TITLE
Add contract profiling instrumentation to combinators defined by TR.

### PR DESCRIPTION
**Pull request by stamourv**
Aside from `Any`, I'm not sure how to trigger those contracts reliably (without causing them to blow up), which I'd like to do for testing. Any suggestions?

### CODE REVIEW

**Comment by takikawa** [comment]
The examples in succeed tests should work. Like https://github.com/racket/typed-racket/blob/master/typed-racket-test/succeed/sealing-contract-1.rkt and https://github.com/racket/typed-racket/blob/master/typed-racket-test/succeed/opaque-object-contract.rkt

**Comment by takikawa** [comment]
BTW, there is also a custom contract for evts in TR. Should that be instrumented too?

**Comment by stamourv** [comment]
Re tests: Ok, will have a look at those.
Re `evt/c`: It basically reuses Racket's `evt/c`'s except for one case that errors right away, so the instrumentation in `evt/c` should do the job.

**Comment by stamourv** [comment]
Merged, thanks!

**Pull request closed without merging**
