### PR TITLE
Unit tests for fl>= typechecking

### PR DESCRIPTION
**Pull request by miraleung**
Tests for issue #115 and followup to pull request #124.

### CODE REVIEW

**Comment by shekari** [comment]
To actually run the unit tests there are a couple of ways.
```racket typed-racket-test/run.rkt --unit``` or ```racket typed-racket-test/unit-tests/typecheck-tests.rkt``` the former runs all the unit tests where the later runs just the typecheck tests.

**Comment by miraleung** [comment]
Thanks Eric. I was using `raco test` as described [here](http://blog.racket-lang.org/2012/11/tutorial-contributing-to-racket.html), so I didn't catch those errors. The [Racket style guide](http://docs.racket-lang.org/style/Units_of_Code.html) didn't mention anything about whitespace and my editor is set to automatically remove them, but I'll make sure these don't get changed in the future. 

All the new tests in my latest push pass, although I'm not sure whether some of the `fl>=` ones should be passing, such as:

```
[tc-e/t 
  (lambda: ([x : Flonum] [y : Flonum-Zero])
    (values (fl<= x y) (fl>= x y)))
  (t:-> -Flonum -FlonumZero
        (make-Values (list
                       (-result -Boolean (-FS (-filter -NonPosFlonum 0) -top))
                       (-result -Boolean)))]
```
Should the last line be `(-result -Boolean (-FS (-filter -NonNegFlonum 0) -top))`?

**Comment by endobson** [comment]
I'm confused on how those tests are passing for you because they are not for me, and don't seem like they should pass.

https://gist.github.com/endobson/b8d141a04c4a317dc696

Other than that this is looking good, you may also want to rebase this ontop of the current HEAD to pick up the changes that were made to the comparison operations.

Also minor nit, but predicate is usually in reference to one argument procedures I would refer to these as 'comparison' operators/functions.

**Comment by miraleung** [comment]
Thanks Eric, those tests are fixed now. There was one that seemed to be passing for you but wasn't for me (line 3719), and since the types looked off, I updated that one as well.

**Comment by samth** [comment]
Merged.

**Pull request closed without merging**
