### PR TITLE
Move unsupported `for*/` forms to the unsupported section

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by stamourv** [comment]
`for/flvector:` (with a colon) and co are defined and exported. `for/flvector` (no colon) and co are not.
The right solution (IMO) would be to export those under both names.

**Comment by AlexKnauth** [comment]
That's about https://github.com/racket/typed-racket/issues/489, which is separate from this pull request.

**Comment by stamourv** [comment]
Ah. I saw the two as being together.
If the typechecker can't deal with the expansion of `for/flvector` and co, then the change you're proposing makes sense.

**Comment by AlexKnauth** [comment]
This isn't about moving `for/flvector`; this is about moving the `for*/` variants so that they're together with their `for/` partners.

**Comment by stamourv** [comment]
Oops. That's what I meant. See my previous statement with `*` added where necessary.

**Comment by AlexKnauth** [comment]
So should this be merged?

**Comment by stamourv** [comment]
If the typechecker can't deal with their expansion, yes.

**Pull request merged**
