### PR TITLE
Add typed/file/md5, typed/web-server/http.rkt, typed/web-server/confi…

### PR DESCRIPTION
**Pull request by wargrey**
…guration/responders.rkt

### CODE REVIEW

**Comment by lexi-lambda** [comment]
1. `typed/file/md5` is already provided by `typed-racket-lib`, so adding it to `typed-racket-more` is an error.
2. Using `{`braces`}` is a little unorthodox in traditional Racket style. I don't have any opposition to them, myself, but keeping things normalized in the TR repo might be worthwhile, though it's probably not a big problem in `typed-racket-more`. Do you have an opinion, @samth?

**Comment by wargrey** [comment]
Sorry, I should tell the details.
In my point of view, `{}` indicates that this is a `Data Expression` and will not evaluated as normal `Racket Expression`. So the only purpose of `{}` is making it easier to parse by eyes. Nonetheless, I do not insist on this style.

**Comment by samth** [comment]
I think we should follow the [style guide](http://docs.racket-lang.org/style/), which doesn't recommend using `{}`.

**Comment by samth** [comment]
Thanks for the new wrappers!

**Pull request closed without merging**
