### PR TITLE
Don't provide Unit from typed/racket/base

### PR DESCRIPTION
**Pull request by AlexKnauth**
fixes https://github.com/racket/typed-racket/issues/234

### CODE REVIEW

**Comment by samth** [comment]
Looks good once the tests pass.

**Comment by AlexKnauth** [comment]
Should this also be added to the release branch?

**Comment by samth** [comment]
I'd prefer not to, since we've basically frozen things. What do other people think, @stamourv @takikawa?

**Comment by AlexKnauth** [comment]
But then the name collision would be there in the release, and code could end up relying on it being provided by base, right?

**Comment by samth** [comment]
@AlexKnauth that's a good point, but the name collision is there in `typed/racket` already.

**Comment by AlexKnauth** [comment]
Should I merge now? (to master)

**Comment by stamourv** [comment]
Aren't we due for another candidate / round of TR testing anyway? In which case, we may be able to bring that change in.

**Comment by samth** [comment]
Yes, merging to master is definitely right, regardless of the release issue.

**Comment by AlexKnauth** [comment]
If you're doing another round of testing anyway, it sounds like it could be added and tested properly with that.

**Comment by rfindler** [comment]
We find it difficult to get everyone to run their tests the first time and
since most of them are run now, it is unlikely we'll get them run a second
time.

Can you say more about why this change is important? Is there a problem
that's new to this release or is the problem already present in the last
release?

**Comment by samth** [comment]
This is a problem new to this release. `typed/racket/base` provides a binding it shouldn't, `Unit`, and fixing it later would be backwards incompatible.

**Comment by rfindler** [comment]
Sounds like something that we should consider as a change to the release,
then.

Robby

**Comment by samth** [comment]
I have merged these commits into the `release` branch.

**Pull request merged**
