### PR TITLE
Provide TR analogue of the web-server's response/empty convenience function

### PR DESCRIPTION
**Pull request by jessealama**
Should I also bump the version of typed-racket-more?

### CODE REVIEW

**Comment by samth** [comment]
Will this work on tomorrow's snapshot?

**Comment by jessealama** [comment]
Hmm, it looks like I'm one step ahead: the current version of the web server is 1.5, not 1.6 as I thought. I'll dump the commit that broke the build.

cc @jeapostrophe

**Comment by samth** [comment]
This broke tests here: http://drdr.racket-lang.org/53392/racket/share/pkgs/typed-racket-more/typed/web-server/http.rkt

@jessealama do you know what went wrong?

**Comment by jessealama** [comment]
Looks like you fixed this -- thanks! Sorry for the trouble.

**Pull request merged**
