### PR TITLE
Don't provide Unit from typed/racket/base

### PR DESCRIPTION
**Pull request by AlexKnauth**
fixes https://github.com/racket/typed-racket/issues/234

### CODE REVIEW

**Comment by samth** [comment]
Looks good.

**Comment by samth** [comment]
Also, in the future, if you use your fork of `typed-racket` rather than pushing to branches in this repo, we get less email.

**Comment by AlexKnauth** [comment]
Yes, that was an accident.

**Comment by AlexKnauth** [comment]
I messed up anyway, I'll re-open from a branch on my fork.

**Comment by AlexKnauth** [comment]
Replaced by https://github.com/racket/typed-racket/pull/236

**Pull request closed without merging**
