### PR TITLE
Add typed/racket/random

### PR DESCRIPTION
**Pull request by takikawa**
Should probably specify a package dependency on a newer "base".

### CODE REVIEW

**Comment by samth** [comment]
Didn't the type of random also change?

**Comment by stamourv** [comment]
@takikawa: Depending on the current version of base should be fine. It's not a released version.

**Comment by takikawa** [comment]
I'm actually not sure what the type of `random` should be. It's currently this:

````
[random
  (cl->* (->opt -PosFixnum [-Pseudo-Random-Generator] -NonNegFixnum)
         (->opt -Int [-Pseudo-Random-Generator] -Nat)
         (->opt [-Pseudo-Random-Generator] -Flonum))]
````

so now that it has min and max arguments, should those be PosFixnum or do we need 4 cases here or something?

**Comment by samth** [comment]
I think you can rely on the error when the min is bigger than the max to reduce the number of cases.

**Comment by stamourv** [comment]
There should be cases for these arguments to be fixnums, but there should also be cases where they're allowed to be arbitrary Integers.

**Pull request merged**
