### PR TITLE
fix duplicated evaluation of vector-expr after optimizing known-length vector-op

### PR DESCRIPTION
**Pull request by yjqww6**
```
#lang typed/racket

(define x 0)
(vector-ref (vector (set! x (+ x 1))) 0)
x
```
This program yields 2 currently.

### CODE REVIEW

**Comment by yjqww6** [comment]
`nonrecoverable invalid memory reference`
This error message from the failed cs ci seems like a segfault during gc, which I think is not very likely to relate to this pull request.
Probably, this expose a severe bug in racketcs.

**Comment by yjqww6** [comment]
Ran ci on a branch even with master and got the same problem, so recent changes to RacketCS might be problematic.
https://github.com/yjqww6/typed-racket/runs/1060799964

**Comment by samth** [comment]
cc @mflatt

**Comment by mflatt** [comment]
I haven't been able to replicate the problem, so far. Is `xvfb-run racket -l typed-racket-test -- --int` the right thing to run?

**Comment by yjqww6** [comment]
If it did related to racketcs changes, it should happen between Aug 28 and Sept 2. But probably we should re-run the ci to see what happen since there are many changes to racket and typed-racket last week.
In worst case, it may need to use exactly the same docker image and scripts with ci config to setup such an environment.

**Comment by samth** [comment]
That is indeed the command that failed. Did you try the snapshot that would have been current on the 7th?

**Comment by yjqww6** [comment]
I cannot reproduce on my machine using a snapshot from ci-snapshot.racket-lang.org either.
But it could be replicated in ci consistently,
1. https://github.com/yjqww6/typed-racket/actions/runs/247346705 - even with master, fail with same problem
2. https://github.com/yjqww6/typed-racket/actions/runs/247673432 - 1 commit behind master(to avoid failing earlier), but change ci to use racketcs 7.8,  doesn't have this problem.
3. https://github.com/yjqww6/typed-racket/actions/runs/247711415 - even with master, but change image to ubuntu 18.04, fail with same problem

**Comment by yjqww6** [comment]
I have created an issue https://github.com/racket/racket/issues/3397 to let this PR serves for its original purpose.

**Comment by samth** [comment]
I will run the tests manually so we can merge this.

**Comment by samth** [comment]
All the tests passed; I merged.

**Pull request merged**
