### PR TITLE
Cancel marks for 'disappeared-use ids in colon macros

### PR DESCRIPTION
**Pull request by btlachance**
Fixes check-syntax arrows for the id and optional second :

### CODE REVIEW

**Comment by AlexKnauth** [comment]
This looks good to me, but is there anyone with any objection to merging this?

**Comment by samth** [comment]
@btlachance Can you give an example program that this fixes?

**Comment by AlexKnauth** [comment]
I tried it with this program:
```racket
#lang typed/racket
(: x : Real)
(define x 3)
```

**Comment by samth** [comment]
Ok, looks good to me.

**Comment by btlachance** [comment]
D'oh, that makes sense to have an example.. Thanks for providing one, Alex

**Pull request merged**
