### PR TITLE
syntax error for require/typed in untyped code

### PR DESCRIPTION
**Pull request by AlexKnauth**
see http://www.mail-archive.com/racket-users@googlegroups.com/msg26916.html

### CODE REVIEW

**Comment by samth** [comment]
Looks right to me, but the error message could be a little more informative.

**Comment by AlexKnauth** [comment]
How? What other information would you want to provide?

**Comment by samth** [comment]
I just worry that "typed context" won't be clear to everyone.

**Comment by AlexKnauth** [comment]
Can you think of a better way of putting it?
Can only be used with a typed language, maybe?
And anyway, it would be clearer than not giving a syntax-error and then putting out a runtime contract violation about promising `#f`, right?

**Comment by samth** [comment]
How about "in a typed module"?

**Comment by AlexKnauth** [comment]
Is this good?

**Comment by samth** [comment]
Looks good to me.

**Comment by AlexKnauth** [comment]
Um, are you going to merge this?

**Comment by samth** [comment]
Yes, soon.

**Comment by samth** [comment]
Unfortunately, this fails several tests on my machine, as follows:

```
[samth@huor:~/.../extra-pkgs/typed-racket/typed-racket-test (master) plt] r succeed/pr11171.rkt
succeed/pr11171.rkt:10:2: require/typed: only allowed in a typed module
  in: (require/typed (quote UNTYPED) (struct IntTree ((elem : Integer) (left : IntTree) (right : IntTree))))
  context...:
   /home/samth/sw/plt/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/base-env/prims-contract.rkt:142:2
```

**Comment by AlexKnauth** [comment]
Then how did the Travis CI build pass?

**Comment by samth** [comment]
The Travis tests don't run the tests, unfortunately.

**Comment by AlexKnauth** [comment]
Could that test be failing because there's no #%module-begin around it?

**Comment by AlexKnauth** [comment]
Why doesn't Travis run the tests?

**Comment by samth** [comment]
Travis doesn't run the tests because it's non-trival to set it up right. Just installing TR and all its dependencies from a minimal install takes longer than 40 minutes on Travis, so we can't do that. The alternative is to start from a regular snapshot, but that requires trickery to install all the packages correctly, which I haven't made work yet.

**Comment by AlexKnauth** [comment]
Would raco pkg install --update-deps work, or are the catalogs for snapshots not set up for that?  If I remember correctly, they aren't, but if they were, would that work?

**Comment by samth** [comment]
The problem is that we need to install several packages at once, and not from the catalog, but from the local checkout.

**Comment by AlexKnauth** [comment]
Oh, do you mean install `typed-racket-lib`, `,typed-racket-more`, `typed-racket-test` etc.?
Or do you mean the dependancies with the correct versions?

**Comment by samth** [comment]
I mean the former. We have a checkout w/ 5 packages in it, and a racket install with different versions of those packages.

**Comment by AlexKnauth** [comment]
Why wouldn't raco pkg update with the directories work then?

**Comment by samth** [comment]
You need to do them all simultaneously (plus, what if a pull request adds a new package?). Anyway, if you have an idea, just creating a TR pull request is enough to test it -- I haven't found a good solution yet, but maybe you will.

**Comment by samth** [comment]
Merged.

**Pull request closed without merging**
