### PR TITLE
add typed/racket/match

### PR DESCRIPTION
**Pull request by bennn**
Simple copy/paste fix for #653 . I didn't see a better way / how to use `opt-lambda-property`.

### CODE REVIEW

**Comment by samth** [comment]
I think this is a bad idea. We should avoid copy and paste like this unless
absolutely necessary.

Can we just add a simple syntax property to lambda in racket/base?

**Comment by bennn** [comment]
I'm not sure how the property would work. Do you mean `opt-lambda-property` and `kw-lambda-property`? What values do those properties expect?


Another thing I thought about (but couldn't get to work) was having `typed/racket/match` expand to `define/match` with a property attached. Something like:

```
(define-syntax (-define/match stx)
  (syntax-property #`(define/match . #,(cdr (syntax-e stx))) ??? ???))
```

**Comment by samth** [comment]
Yes, I'm suggesting that `typed/racket` should just recognize a property added by `lambda` and/or `define` itself. I think the TR properties don't have any interesting value; they're just set to `#t`.

**Comment by jackfirth** [comment]
Question from the peanut gallery: would it solve this problem if `define` and/or `lambda` were syntax parameters?

**Comment by samth** [comment]
A syntax parameter such as `current-lambda` that `match` could use would indeed be helpful here.

**Pull request closed without merging**
