### PR TITLE
Simplify the type for zero

### PR DESCRIPTION
**Pull request by shekari**
With the first commit I'm not sure how we would want to organize the code. Do we want to try and make the lazy-require not necessary?

### CODE REVIEW

**Comment by samth** [comment]
@shekari I think the `lazy-require` is probably necessary -- `subst-type` ends up using `subtype`.

@andmkent can you review this?

**Comment by stamourv** [comment]
The numeric parts LGTM.

**Comment by shekari** [comment]
@andmkent any comments?

**Comment by andmkent** [comment]
(sorry for not seeing this till now)

Looks great! 

I actually did something similar *just* for dependent function subtyping (this approach looks nicer than what I did). This should help reduce special casing for dependent functions.

**Pull request closed without merging**
