### PR TITLE
Add contract-equivalent? for opaque objects

### PR DESCRIPTION
**Pull request by bennn**

### CODE REVIEW

**Comment by rfindler** [comment]
Not that anyone asked me :), but this code looks right to me.

**Comment by bennn** [comment]
I'll restart travis after today's nightly build --- then the tests should pass

**Comment by bennn** [comment]
on second thought --- @samth is it okay to merge this without travis? I'd like to use the commit here to start some benchmarks tonight.

(If not, I can cherry-pick the commit from my fork, but it would be easier to have the commit on TR's master)

**Comment by samth** [comment]
Yes, if you need to that's fine. Someday I'm going to switch to https://graydon.livejournal.com/186550.html but today is not that day ;)

**Comment by bennn** [comment]
https://github.com/racket/typed-racket/commit/4c5ea6f93d197a942592d36466f53dad26e9b19d

**Pull request closed without merging**
